# Site settings
name: 池圣齐的博客
email: 122377305@qq.com
author: csq
url: https://jqsc.github.io/chishengqi.github.io/
baseurl: "https://jqsc.github.io/chishengqi.github.io/"  #根目录
#baseurl: ""  #根目录
description: 假如生活欺骗了你，不要悲伤，不要哭泣。
motto: 我们笑着说再见，却深知再见遥遥无期。
banner: 我想带你去看绚丽的山峦，去看秀丽的溪谷，这份心情，人类是如何称呼的呢。
excerpt_separator:  '<!-- more -->' #文章摘要
paginate: 5
paginate_path: "page:num"
plugins: [jekyll-paginate]
exclude: ['README.md']
github_username: chishengqi
highlighter: rouge
encoding: utf-8